# NumPy Arrays

NumPy is the foundation of numerical computing in Python.

In [3]:
import numpy as np

# Check version
print(f"NumPy version: {np.__version__}")

NumPy version: 1.26.4


## 1. Creating Arrays

In [4]:
# From Python list
arr = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr}")
print(f"Shape: {arr.shape}")
print(f"Dtype: {arr.dtype}")

1D array: [1 2 3 4 5]
Shape: (5,)
Dtype: int32


In [5]:
# 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{matrix}")
print(f"Shape: {matrix.shape}")

2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [6]:
# Common creation functions
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identity = np.eye(3)
empty = np.empty((2, 2))  # Uninitialized

print(f"Zeros:\n{zeros}\n")
print(f"Identity:\n{identity}")

Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Ranges
range_arr = np.arange(0, 10, 2)  # Start, stop, step
linspace = np.linspace(0, 1, 5)  # Start, stop, num points

print(f"Arange: {range_arr}")
print(f"Linspace: {linspace}")

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [8]:
# Random arrays
np.random.seed(42)  # For reproducibility

uniform = np.random.rand(3, 3)  # Uniform [0, 1)
normal = np.random.randn(3, 3)  # Standard normal
integers = np.random.randint(0, 10, size=(3, 3))

print(f"Uniform:\n{uniform}\n")
print(f"Normal:\n{normal}")

Uniform:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Normal:
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]


## 2. Array Indexing and Slicing

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic indexing
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")

# Slicing [start:stop:step]
print(f"First three: {arr[:3]}")
print(f"Evens: {arr[::2]}")
print(f"Reversed: {arr[::-1]}")

First element: 0
Last element: 9
First three: [0 1 2]
Evens: [0 2 4 6 8]
Reversed: [9 8 7 6 5 4 3 2 1 0]


In [10]:
# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix:\n{matrix}\n")

print(f"Element [1,2]: {matrix[1, 2]}")
print(f"First row: {matrix[0, :]}")
print(f"First column: {matrix[:, 0]}")
print(f"Submatrix:\n{matrix[:2, 1:]}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element [1,2]: 6
First row: [1 2 3]
First column: [1 4 7]
Submatrix:
[[2 3]
 [5 6]]


In [11]:
# Boolean indexing (very useful for filtering!)
arr = np.array([1, -2, 3, -4, 5])

mask = arr > 0
print(f"Mask: {mask}")
print(f"Positive elements: {arr[mask]}")

# Shorthand
print(f"Negative elements: {arr[arr < 0]}")

Mask: [ True False  True False  True]
Positive elements: [1 3 5]
Negative elements: [-2 -4]


In [12]:
# Fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])

print(f"Selected: {arr[indices]}")

Selected: [10 30 50]


## 3. Array Operations

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")
print(f"Power: {a ** 2}")
print(f"Divide: {a / b}")

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Power: [1 4 9]
Divide: [0.25 0.4  0.5 ]


In [14]:
# Universal functions (ufuncs)
arr = np.array([1, 4, 9, 16])

print(f"Square root: {np.sqrt(arr)}")
print(f"Exponential: {np.exp(np.array([0, 1, 2]))}")
print(f"Log: {np.log(np.array([1, np.e, np.e**2]))}")
print(f"Sin: {np.sin(np.array([0, np.pi/2, np.pi]))}")

Square root: [1. 2. 3. 4.]
Exponential: [1.         2.71828183 7.3890561 ]
Log: [0. 1. 2.]
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [15]:
# Aggregation functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Sum: {np.sum(arr)}")
print(f"Sum by rows: {np.sum(arr, axis=1)}")
print(f"Sum by columns: {np.sum(arr, axis=0)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr)}")
print(f"Min: {np.min(arr)}, Max: {np.max(arr)}")

Sum: 21
Sum by rows: [ 6 15]
Sum by columns: [5 7 9]
Mean: 3.5
Std: 1.707825127659933
Min: 1, Max: 6


## 4. Reshaping Arrays

In [16]:
arr = np.arange(12)
print(f"Original: {arr} (shape: {arr.shape})")

# Reshape
reshaped = arr.reshape(3, 4)
print(f"Reshaped (3x4):\n{reshaped}")

# -1 means "infer this dimension"
reshaped2 = arr.reshape(2, -1)
print(f"Reshaped (2x?):\n{reshaped2}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] (shape: (12,))
Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2x?):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [17]:
# Flatten and ravel
matrix = np.array([[1, 2], [3, 4]])

print(f"Flatten: {matrix.flatten()}")
print(f"Ravel: {matrix.ravel()}")  # Returns view when possible

Flatten: [1 2 3 4]
Ravel: [1 2 3 4]


In [18]:
# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original (2x3):\n{matrix}")
print(f"Transposed (3x2):\n{matrix.T}")

Original (2x3):
[[1 2 3]
 [4 5 6]]
Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]


In [19]:
# Adding dimensions
arr = np.array([1, 2, 3])
print(f"Original shape: {arr.shape}")

# Add axis
row = arr[np.newaxis, :]  # or arr.reshape(1, -1)
col = arr[:, np.newaxis]  # or arr.reshape(-1, 1)

print(f"Row vector shape: {row.shape}")
print(f"Column vector shape: {col.shape}")

Original shape: (3,)
Row vector shape: (1, 3)
Column vector shape: (3, 1)


## 5. Concatenation and Splitting

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stack
v_stacked = np.vstack([a, b])
print(f"Vertical stack:\n{v_stacked}\n")

# Horizontal stack
h_stacked = np.hstack([a, b])
print(f"Horizontal stack:\n{h_stacked}")

Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
# Concatenate with axis
concat_0 = np.concatenate([a, b], axis=0)  # Same as vstack
concat_1 = np.concatenate([a, b], axis=1)  # Same as hstack

print(f"Concat axis=0 shape: {concat_0.shape}")
print(f"Concat axis=1 shape: {concat_1.shape}")

Concat axis=0 shape: (4, 2)
Concat axis=1 shape: (2, 4)


In [22]:
# Splitting
arr = np.arange(9).reshape(3, 3)
print(f"Original:\n{arr}\n")

# Split into 3 parts
splits = np.split(arr, 3, axis=0)
for i, s in enumerate(splits):
    print(f"Split {i}: {s.flatten()}")

Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Split 0: [0 1 2]
Split 1: [3 4 5]
Split 2: [6 7 8]


## 6. Copying Arrays

In [23]:
# Views vs Copies - IMPORTANT!
original = np.array([1, 2, 3, 4, 5])

# View (shares memory)
view = original[1:4]
view[0] = 999
print(f"After modifying view: {original}")  # Original is modified!

# Copy (independent)
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 999
print(f"After modifying copy: {original}")  # Original is unchanged

After modifying view: [  1 999   3   4   5]
After modifying copy: [1 2 3 4 5]


## 7. Exercises

In [24]:
# Exercise 1: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
# Hint: use np.diag with k parameter

# Your code here
result = np.diag([1, 2, 3, 4], k=-1)
print(result)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
# Exercise 2: Normalize an array to have mean=0 and std=1
arr = np.array([10, 20, 30, 40, 50], dtype=float)

# Your code here
normalized = (arr - np.mean(arr)) / np.std(arr)
print(f"Normalized: {normalized}")
print(f"Mean: {normalized.mean():.6f}, Std: {normalized.std():.6f}")

Normalized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean: 0.000000, Std: 1.000000


In [26]:
# Exercise 3: Find indices of maximum values in each row
matrix = np.random.randint(0, 100, size=(3, 5))
print(f"Matrix:\n{matrix}")

# Your code here
max_indices = np.argmax(matrix, axis=1)
print(f"Max indices per row: {max_indices}")

Matrix:
[[72 38 17  3 88]
 [59 13  8 89 52]
 [ 1 83 91 59 70]]
Max indices per row: [4 3 2]
